# Generated by Django 6.0.8 on 2026-10-08 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=500)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("customers", "Customer records"),
                            ("sales", "Quotations"),
                            ("delivery", "Jobs and delivery history"),
                            ("finance", "Invoices and sequences"),
                            ("payments", "Daraja payment diagnostics"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_support_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_access_grants",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-granted_at", "id"]},
        ),
        migrations.CreateModel(
            name="SupportAccessAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("model_label", models.CharField(max_length=100)),
                ("object_pk", models.CharField(blank=True, max_length=100)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("list", "List viewed"), ("object", "Record viewed")],
                        max_length=12,
                    ),
                ),
                (
                    "support_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="accounts.supportaccess",
                    ),
                ),
            ],
            options={"ordering": ["-accessed_at", "id"]},
        ),
    ]
