# Generated by Django 5.2.7 on 2026-10-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0002_supportaccess_supportaccessauditevent")]

    operations = [
        migrations.CreateModel(
            name="EndpointRateLimitBucket",
            fields=[
                (
                    "key_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={"ordering": ["expires_at"]},
        ),
    ]
