from django.contrib import admin
from django.urls import path

from accounts.views import csrf_token, session_view, organizations_view
from customers.views import customer_detail_view, customers_view
from quotations.views import (
    quotation_detail_view,
    quotations_view,
    quotation_transition_view,
    quotation_revision_view,
)
from quotations.job_views import (
    job_assignment_create_view,
    job_assignment_remove_view,
    job_detail_view,
    job_note_create_view,
    jobs_view,
)
from invoicing.views import (
    finance_export_view,
    daraja_payment_attempt_create_view,
    daraja_payment_attempt_reconcile_view,
    daraja_payment_attempt_view,
    daraja_stk_callback_view,
    invoice_issue_view,
    invoice_void_view,
    invoices_view,
    payment_allocate_view,
    payment_allocation_reverse_view,
    payment_reverse_view,
    payments_view,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/csrf/", csrf_token),
    path("api/session/", session_view),
    path(
        "api/payments/daraja/sandbox/stk/callback/",
        daraja_stk_callback_view,
        name="daraja-stk-callback",
    ),
    path("api/organizations/", organizations_view, name="organizations"),
    path(
        "api/organizations/<uuid:organization_id>/customers/",
        customers_view,
        name="customers",
    ),
    path(
        "api/organizations/<uuid:organization_id>/customers/<int:customer_id>/",
        customer_detail_view,
        name="customer-detail",
    ),
    path(
        "api/organizations/<uuid:organization_id>/quotations/",
        quotations_view,
        name="quotations",
    ),
    path(
        "api/organizations/<uuid:organization_id>/quotations/<uuid:quotation_id>/",
        quotation_detail_view,
        name="quotation-detail",
    ),
    path(
        "api/organizations/<uuid:organization_id>/quotations/<uuid:quotation_id>/transition/",
        quotation_transition_view,
        name="quotation-transition",
    ),
    path(
        "api/organizations/<uuid:organization_id>/quotations/<uuid:quotation_id>/revise/",
        quotation_revision_view,
        name="quotation-revise",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/",
        jobs_view,
        name="jobs",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/<int:job_id>/",
        job_detail_view,
        name="job-detail",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/<int:job_id>/assignments/",
        job_assignment_create_view,
        name="job-assignment-create",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/<int:job_id>/assignments/<int:assignment_id>/remove/",
        job_assignment_remove_view,
        name="job-assignment-remove",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/<int:job_id>/notes/",
        job_note_create_view,
        name="job-note-create",
    ),
    path(
        "api/organizations/<uuid:organization_id>/invoices/",
        invoices_view,
        name="invoices",
    ),
    path(
        "api/organizations/<uuid:organization_id>/exports/<str:resource>.csv",
        finance_export_view,
        name="finance-export",
    ),
    path(
        "api/organizations/<uuid:organization_id>/jobs/<int:job_id>/invoice/",
        invoice_issue_view,
        name="invoice-issue",
    ),
    path(
        "api/organizations/<uuid:organization_id>/invoices/<uuid:invoice_id>/void/",
        invoice_void_view,
        name="invoice-void",
    ),
    path(
        "api/organizations/<uuid:organization_id>/invoices/<uuid:invoice_id>/daraja/sandbox-attempts/",
        daraja_payment_attempt_create_view,
        name="daraja-attempt-create",
    ),
    path(
        "api/organizations/<uuid:organization_id>/daraja/sandbox-attempts/<uuid:attempt_id>/",
        daraja_payment_attempt_view,
        name="daraja-attempt",
    ),
    path(
        "api/organizations/<uuid:organization_id>/daraja/sandbox-attempts/<uuid:attempt_id>/reconcile/",
        daraja_payment_attempt_reconcile_view,
        name="daraja-attempt-reconcile",
    ),
    path(
        "api/organizations/<uuid:organization_id>/payments/",
        payments_view,
        name="payments",
    ),
    path(
        "api/organizations/<uuid:organization_id>/payments/<uuid:payment_id>/allocate/",
        payment_allocate_view,
        name="payment-allocate",
    ),
    path(
        "api/organizations/<uuid:organization_id>/payments/<uuid:payment_id>/reverse/",
        payment_reverse_view,
        name="payment-reverse",
    ),
    path(
        "api/organizations/<uuid:organization_id>/payment-allocations/<uuid:allocation_id>/reverse/",
        payment_allocation_reverse_view,
        name="payment-allocation-reverse",
    ),
]
