# Generated by Django 6.0.8 on 2026-10-05 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_quotation_series_ids(apps, schema_editor):
    Quotation = apps.get_model("quotations", "Quotation")
    database = schema_editor.connection.alias
    for quotation in Quotation.objects.using(database).all().iterator():
        Quotation.objects.using(database).filter(pk=quotation.pk).update(
            series_id=uuid.uuid4(), revision_number=1
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0002_customer_status_customerstatushistory"),
        ("quotations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="revision_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quotation",
            name="series_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revision",
                to="quotations.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                    ("superseded", "Superseded"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="quotationstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("expired", "Expired"),
                    ("superseded", "Superseded"),
                ],
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_quotation_series_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("series_id", "revision_number"),
                name="unique_quotation_series_revision",
            ),
        ),
    ]
