# Generated by Django 6.0.8 on 2026-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="correction_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
