# Generated by Django 6.0.8 on 2026-10-05 19:52

from django.db import migrations, models


def backfill_invoice_customer_name(apps, schema_editor):
    Invoice = apps.get_model("invoicing", "Invoice")
    Customer = apps.get_model("customers", "Customer")
    database = schema_editor.connection.alias
    for invoice in Invoice.objects.using(database).all().iterator():
        customer_name = (
            Customer.objects.using(database)
            .filter(pk=invoice.customer_id)
            .values_list("name", flat=True)
            .first()
            or ""
        )
        Invoice.objects.using(database).filter(pk=invoice.pk).update(
            customer_name=customer_name
        )


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0002_invoice_correction_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(backfill_invoice_customer_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(max_length=200),
        ),
    ]
