# Generated by Django 6.0.8 on 2026-10-06 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0002_customer_status_customerstatushistory"),
        ("invoicing", "0004_payment_paymentallocation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DarajaPaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=5, max_digits=30)),
                ("phone_number", models.CharField(max_length=12)),
                ("idempotency_key", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("review", "Needs review"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(max_length=120, null=True, unique=True),
                ),
                ("merchant_request_id", models.CharField(blank=True, max_length=120)),
                ("result_code", models.CharField(blank=True, max_length=40)),
                ("result_description", models.CharField(blank=True, max_length=240)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja_payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja_payment_attempts",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja_payment_attempts",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja_payment_attempts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja_attempt",
                        to="invoicing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DarajaCallbackEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_request_id", models.CharField(max_length=120, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("delivery_count", models.PositiveIntegerField(default=1)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("last_received_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="callback_events",
                        to="invoicing.darajapaymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="darajapaymentattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="unique_daraja_attempt_idempotency_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="darajapaymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="daraja_attempt_amount_positive",
            ),
        ),
    ]
